language: node_js

node_js:
    - '8'

if: NOT (tag IS present OR commit_message =~ /^chore\(release\):/)

install:
    - npm ci

script:
    - npm run lint
    - npm run test:unit
    - npm run test:func

    

before_deploy: npm run release

deploy:
    provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
        branch: release
